services:
  app:
    build: .
    ports:
      - "5010:5010"
    restart: unless-stopped
    volumes:
      - ./:/app/data
    environment:
      - KITE_API_KEY=
      - KITE_API_SECRET=
      - data_sql_url=
      - AUTH_USER=
      - AUTH_PASSWORD=
      - apikey=
      - JWT_EXPIRATION_DAYS=5
      - JWT_SECRET_KEY=
      - RATE_LIMIT_PER_MINUTE=180
